export const portfolioData = {
  personal: {
    name: "Aymar Avilés",
    title: "Full Stack Developer & AI Workflow Architect",
    location: "Guayaquil, Ecuador",
    email: "avilezaymar70@gmail.com",
    whatsapp: "+593 990069857",
    whatsappUrl: "https://wa.me/593990069857",
    github: "https://github.com/aymaravilez70",
    linkedin: "https://linkedin.com/in/aymar-aviles-ronquillo",
    cvPdf: "/CV_Aymar_Aviles.pdf",
    bio: "Desarrollador web enfocado en crear soluciones de software de alto impacto con React, Next.js, Node.js y Python, integrando automatizaciones inteligentes con IA y n8n.",
  },
  projects: [
    {
      id: "ecosort-ai",
      title: "EcoSort AI",
      category: "IA & Automatización",
      description: "Sistema de clasificación automatizada de excedentes con IA y visión artificial. Orquestado con n8n y microservicios en Python.",
      tags: ["Next.js", "Python", "n8n", "Computer Vision", "FastAPI"],
      link: "/proyectos/ecosort-ai",
    },
    {
      id: "waspbot",
      title: "WaspBot",
      category: "IA & Automatización",
      description: "Bot para WhatsApp desarrollado en Node.js con procesamiento de comandos en tiempo real, creación de stickers y búsqueda de música.",
      tags: ["Node.js", "WhatsApp API", "Automation", "JavaScript"],
      link: "/proyectos/waspbot",
    },
    {
      id: "melopatitas",
      title: "MeloPatitas",
      category: "Aplicaciones Web",
      description: "Plataforma web de rescate animal para gestión de adopciones, donaciones y fichas médicas con panel administrativo.",
      tags: ["React", "Next.js", "Tailwind CSS", "PostgreSQL", "Node.js"],
      link: "/proyectos/melopatitas",
    },
    {
      id: "nocion",
      title: "Nocion",
      category: "Aplicaciones Web",
      description: "Suite de productividad y hábitos diarios con tableros interactivos, métricas de cumplimiento y calendarios.",
      tags: ["React", "TypeScript", "Tailwind CSS", "LocalStorage API"],
      link: "/proyectos/nocion",
    },
    {
      id: "hpo-shop",
      title: "HPO SHOP",
      category: "Aplicaciones Web",
      description: "Catálogo de comercio electrónico interactivo y responsivo con filtros dinámicos y arquitectura optimizada.",
      tags: ["React", "JavaScript", "CSS Modules", "REST API"],
      link: "/proyectos/hpo-shop",
    },
    {
      id: "waike",
      title: "Waike Music",
      category: "Sistemas & Móvil",
      description: "Aplicación móvil y web de streaming musical con listas de reproducción inmersivas y control de audio fluido.",
      tags: ["React Native / Web", "Audio API", "UI/UX", "Node.js"],
      link: "/proyectos/waike",
    },
    {
      id: "yale",
      title: "Yale App",
      category: "Sistemas & Móvil",
      description: "Sistema multiplataforma para reproducción sincronizada de audio y video en tiempo real vía WebSockets.",
      tags: ["WebSockets", "Node.js", "React", "Full Duplex"],
      link: "/proyectos/yale",
    },
  ],
  experience: [
    {
      company: "Alvirene Construcción & Ferretería",
      role: "Vendedor & Control de Inventario Digital",
      period: "Jun 2024 — Feb 2025",
      tasks: [
        "Digitalización y control de inventario de 500+ referencias de productos.",
        "Auditorías periódicas de stock y cuadre contable operacional.",
        "Atención comercial y asesoramiento técnico a clientes.",
      ],
      tags: ["Control de Inventario", "Auditoría de Stock", "Gestión Comercial"],
    },
    {
      company: "Farmacia Anthony",
      role: "Especialista en Mantenimiento de Base de Datos",
      period: "Ene 2024 — Jun 2024",
      tasks: [
        "Depuración y actualización de bases de datos de inventario farmacéutico.",
        "Conciliación de 800+ registros de medicamentos asegurando stock exacto.",
        "Resolución de discrepancias operativas en el sistema de facturación.",
      ],
      tags: ["SQL", "Gestión de Datos", "Conciliación de Stock"],
    },
    {
      company: "Punto de Encuentro",
      role: "Asistente de Soporte Técnico & Prácticas",
      period: "Sep 2022 — Mar 2023",
      tasks: [
        "Mantenimiento preventivo y correctivo de equipos de cómputo y redes.",
        "Diagnóstico de fallas en sistemas operativos y atención a incidencias de usuarios.",
        "Capacitación a colaboradores en Microsoft Office y Google Workspace.",
      ],
      tags: ["Soporte Técnico", "Redes & Hardware", "Ofimática"],
    },
  ],
  skills: {
    frontend: ["React 19", "Next.js 15", "TypeScript", "Tailwind CSS", "Three.js", "HTML5 / CSS3"],
    backend: ["Node.js", "Python", "FastAPI", "PHP", "WebSockets", "REST APIs"],
    aiAutomation: ["n8n Workflows", "Agentes Autónomos", "Modelos de Visión", "Webhooks"],
    database: ["PostgreSQL", "MySQL", "Supabase", "Arquitectura Relacional"],
  },
};
